# Generated by Django 5.2.6 on 2025-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('herois', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EquipeModel',
        ),
    ]
