# Generated by Django 5.2.6 on 2025-09-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anos', '0002_anomodel_delete_equipemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=10)),
                ('herois', models.TextField()),
            ],
        ),
    ]
