# Generated by Django 5.2.6 on 2025-09-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimodel',
            name='forca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='imagem',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='inteligencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='poder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='velocidade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroimodel',
            name='alter_ego',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroimodel',
            name='editora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
