# Generated by Django 5.2.6 on 2025-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0002_heroimodel_forca_heroimodel_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimodel',
            name='alter_ego',
        ),
        migrations.RemoveField(
            model_name='heroimodel',
            name='forca',
        ),
        migrations.RemoveField(
            model_name='heroimodel',
            name='inteligencia',
        ),
        migrations.RemoveField(
            model_name='heroimodel',
            name='velocidade',
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='afiliacoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='local_base',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='primeira_aparicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
