# Generated by Django 5.2.6 on 2025-09-14 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0003_remove_heroimodel_alter_ego_remove_heroimodel_forca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herois', to='herois.equipemodel'),
        ),
    ]
