# Generated by Django 5.2.6 on 2025-09-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0004_equipemodel_heroimodel_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimodel',
            name='equipe',
        ),
        migrations.AddField(
            model_name='heroimodel',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='EquipeModel',
        ),
    ]
