# Generated by Django 5.2.6 on 2025-09-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herois', '0005_remove_heroimodel_equipe_heroimodel_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimodel',
            name='descricao',
        ),
    ]
